import React from 'react';
import { MapPin, Utensils, Heart, ExternalLink, Route, Globe, ShoppingBag } from 'lucide-react';

export default function CafeCard({ cafe, isWishlisted, onToggleWishlist, onSelectCafe }) {
  return <article className="rounded-2xl bg-stone-900/90 border border-amber-900/40 hover:border-amber-700/60 shadow-xl transition-all flex flex-col overflow-hidden">
    <div className="p-5 border-b border-stone-800/80 bg-stone-950/40">
      <div className="flex items-start justify-between gap-3"><div className="flex flex-wrap gap-2"><span className="px-2.5 py-1 rounded-lg text-xs font-semibold bg-amber-950/80 border border-amber-800/50 text-amber-300 flex items-center gap-1"><MapPin className="w-3 h-3" />{cafe.zone}</span><span className="px-2.5 py-1 rounded-lg text-xs bg-stone-800 text-stone-300">{cafe.vibeTag}</span>{cafe.quickPickLabel&&<span className="px-2.5 py-1 rounded-lg text-xs font-bold bg-amber-600 text-stone-950">★ {cafe.quickPickLabel}</span>}</div><button onClick={()=>onToggleWishlist(cafe.id)} className="p-2 rounded-xl bg-stone-900 border border-stone-800"><Heart className={`w-4 h-4 ${isWishlisted?'fill-rose-500 text-rose-500':'text-stone-400'}`} /></button></div>
      <div className="flex items-baseline justify-between gap-2 mt-3"><h3 onClick={()=>onSelectCafe(cafe)} className="font-serif text-xl font-bold text-stone-100 hover:text-amber-300 cursor-pointer">{cafe.name}</h3><span className="text-sm font-bold px-2.5 py-1 rounded-md bg-stone-950 border border-emerald-800/60 text-emerald-400 whitespace-nowrap">{cafe.budget}</span></div>
      <p className="text-xs text-stone-400 italic mt-1">Best for: {cafe.bestFor}</p>
    </div>
    <div className="p-5 space-y-3 text-xs sm:text-sm text-stone-300 flex-1"><div className="p-3 rounded-xl bg-stone-950/60 border border-stone-800"><span className="text-amber-400 font-semibold flex items-center gap-1 mb-1"><Utensils className="w-3.5 h-3.5" /> WHAT TO ORDER</span><p>{cafe.whatToOrder}</p></div><div className="p-3 rounded-xl bg-stone-950/60 border border-stone-800"><span className="text-emerald-400 font-semibold flex items-center gap-1 mb-1"><Route className="w-3.5 h-3.5" /> FROM PASCHIM VIHAR</span><p>{cafe.metroRoute}</p></div><div className="p-3 rounded-xl bg-amber-950/30 border border-amber-800/40"><span className="text-amber-300 font-semibold block mb-1">REAL TALK</span><p>{cafe.curatorTake}</p></div></div>
    <div className="grid grid-cols-4 gap-2 p-4 border-t border-stone-800"><a href={cafe.mapsUrl} target="_blank" rel="noreferrer" className="p-2 rounded-lg bg-amber-950 text-amber-300 text-[10px] font-semibold text-center"><MapPin className="w-3 h-3 mx-auto mb-1"/>MAPS</a><a href={cafe.websiteUrl||cafe.mapsUrl} target="_blank" rel="noreferrer" className="p-2 rounded-lg bg-stone-800 text-stone-300 text-[10px] font-semibold text-center"><Globe className="w-3 h-3 mx-auto mb-1"/>WEB</a><a href={cafe.zomatoUrl} target="_blank" rel="noreferrer" className="p-2 rounded-lg bg-red-950/60 text-red-300 text-[10px] font-semibold text-center"><Utensils className="w-3 h-3 mx-auto mb-1"/>ZOMATO</a><a href={cafe.swiggyUrl} target="_blank" rel="noreferrer" className="p-2 rounded-lg bg-orange-950/60 text-orange-300 text-[10px] font-semibold text-center"><ShoppingBag className="w-3 h-3 mx-auto mb-1"/>SWIGGY</a></div>
  </article>;
}
