import React from 'react';
import { Coffee, Heart, QrCode, MapPin, Compass } from 'lucide-react';
import InstagramIcon from './InstagramIcon';

export default function Navbar({ wishlistCount, onOpenWishlist, onOpenInstaModal, activeTab, setActiveTab }) {
  const active = (tab) => activeTab === tab ? 'bg-[#A2AB73]/20 text-[#56602E] border border-[#A2AB73]/45' : 'text-[#685D50] hover:text-[#CC3A63] hover:bg-[#F9F0E0]';
  return <header className="sticky top-0 z-40 bg-[#FFF7EB]/95 backdrop-blur-md border-b border-[#A2AB73]/35 text-[#332B23] shadow-[0_4px_18px_rgba(78,62,38,0.06)]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex items-center justify-between h-20">
    <div className="flex items-center space-x-3 cursor-pointer" onClick={() => setActiveTab('explore')}><div className="w-12 h-12 rounded-2xl bg-[#CC3A63] flex items-center justify-center shadow-lg shadow-[#CC3A63]/20"><Coffee className="w-6 h-6 text-[#FFF7EB]" /></div><div><span className="font-serif text-xl sm:text-2xl font-bold tracking-tight text-[#332B23] flex items-center gap-2">Delhi NCR <span className="text-[#CC3A63] font-sans text-xs uppercase px-2 py-0.5 rounded-full bg-[#F9F0E0] border border-[#A2AB73]/45 tracking-wider">Date Guide</span></span><p className="text-xs text-[#786C5C] hidden sm:block">Curated by @iavinaxh • Budget-Friendly Cafe Hopping</p></div></div>
    <nav className="hidden md:flex items-center space-x-1 lg:space-x-2 font-medium text-sm"><button onClick={()=>setActiveTab('explore')} className={`px-4 py-2 rounded-xl transition-all flex items-center gap-2 ${active('explore')}`}><Compass className="w-4 h-4 text-[#CC3A63]" /><span>Cafes & Places</span></button><button onClick={()=>setActiveTab('quick')} className={`px-4 py-2 rounded-xl transition-all flex items-center gap-2 ${active('quick')}`}><span className="w-2 h-2 rounded-full bg-[#CC3A63] animate-pulse"></span><span>10s Decision</span></button><button onClick={()=>setActiveTab('plans')} className={`px-4 py-2 rounded-xl transition-all ${active('plans')}`}>Ready Plans</button><button onClick={()=>setActiveTab('metro')} className={`px-4 py-2 rounded-xl transition-all flex items-center gap-2 ${active('metro')}`}><MapPin className="w-4 h-4 text-[#56602E]" /><span>Metro Routes</span></button></nav>
    <div className="flex items-center space-x-2 sm:space-x-3"><button onClick={onOpenInstaModal} className="px-3.5 py-2 rounded-xl bg-[#CC3A63] hover:bg-[#B52F55] text-white font-medium text-xs sm:text-sm flex items-center gap-2 transition-colors"><InstagramIcon className="w-4 h-4" /><span className="hidden sm:inline">@iavinaxh</span><QrCode className="w-3.5 h-3.5 opacity-80" /></button><button onClick={onOpenWishlist} className="relative p-2.5 rounded-xl bg-[#F9F0E0] text-[#56602E] border border-[#A2AB73]/45 flex items-center gap-1.5 hover:border-[#CC3A63]/50 transition-colors"><Heart className={`w-5 h-5 ${wishlistCount > 0 ? 'text-[#CC3A63] fill-[#CC3A63]' : ''}`} />{wishlistCount > 0 && <span className="w-5 h-5 rounded-full bg-[#CC3A63] text-white text-xs font-bold flex items-center justify-center">{wishlistCount}</span>}</button></div>
  </div><div className="md:hidden flex items-center justify-around py-2.5 border-t border-[#A2AB73]/25 font-medium text-xs text-[#685D50]"><button onClick={()=>setActiveTab('explore')} className={active('explore')}>Cafes</button><button onClick={()=>setActiveTab('quick')} className={active('quick')}>10s Quick</button><button onClick={()=>setActiveTab('plans')} className={active('plans')}>Plans</button><button onClick={()=>setActiveTab('metro')} className={active('metro')}>Metro</button></div></div></header>;
}
