import React from 'react';
import { Coffee, Heart, QrCode, MapPin, Compass } from 'lucide-react';
import InstagramIcon from './InstagramIcon';

export default function Navbar({ wishlistCount, onOpenWishlist, onOpenInstaModal, activeTab, setActiveTab }) {
  const active = (tab) => activeTab === tab ? 'bg-amber-900/50 text-amber-300 border border-amber-700/50' : 'text-stone-300 hover:text-amber-200 hover:bg-stone-900/60';
  return <header className="sticky top-0 z-40 bg-stone-950/80 backdrop-blur-md border-b border-amber-900/30 text-stone-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex items-center justify-between h-20">
    <div className="flex items-center space-x-3 cursor-pointer" onClick={() => setActiveTab('explore')}><div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-amber-700 via-amber-600 to-amber-500 flex items-center justify-center shadow-lg shadow-amber-900/40"><Coffee className="w-6 h-6 text-stone-950" /></div><div><span className="font-serif text-xl sm:text-2xl font-bold tracking-tight text-amber-100 flex items-center gap-2">Delhi NCR <span className="text-amber-500 font-sans text-xs uppercase px-2 py-0.5 rounded-full bg-amber-950/80 border border-amber-800/50 tracking-wider">Date Guide</span></span><p className="text-xs text-stone-400 hidden sm:block">Curated by @iavinaxh • Budget-Friendly Cafe Hopping</p></div></div>
    <nav className="hidden md:flex items-center space-x-1 lg:space-x-2 font-medium text-sm"><button onClick={()=>setActiveTab('explore')} className={`px-4 py-2 rounded-xl transition-all flex items-center gap-2 ${active('explore')}`}><Compass className="w-4 h-4 text-amber-400" /><span>Cafes & Places</span></button><button onClick={()=>setActiveTab('quick')} className={`px-4 py-2 rounded-xl transition-all flex items-center gap-2 ${active('quick')}`}><span className="w-2 h-2 rounded-full bg-amber-500 animate-pulse"></span><span>10s Decision</span></button><button onClick={()=>setActiveTab('plans')} className={`px-4 py-2 rounded-xl transition-all ${active('plans')}`}>Ready Plans</button><button onClick={()=>setActiveTab('metro')} className={`px-4 py-2 rounded-xl transition-all flex items-center gap-2 ${active('metro')}`}><MapPin className="w-4 h-4 text-emerald-400" /><span>Metro Routes</span></button></nav>
    <div className="flex items-center space-x-2 sm:space-x-3"><button onClick={onOpenInstaModal} className="px-3.5 py-2 rounded-xl bg-gradient-to-r from-pink-600 via-rose-600 to-amber-600 text-white font-medium text-xs sm:text-sm flex items-center gap-2"><InstagramIcon className="w-4 h-4" /><span className="hidden sm:inline">@iavinaxh</span><QrCode className="w-3.5 h-3.5 opacity-80" /></button><button onClick={onOpenWishlist} className="relative p-2.5 rounded-xl bg-stone-900/90 text-stone-300 border border-stone-800/80 flex items-center gap-1.5"><Heart className={`w-5 h-5 ${wishlistCount > 0 ? 'text-rose-500 fill-rose-500' : ''}`} />{wishlistCount > 0 && <span className="w-5 h-5 rounded-full bg-rose-600 text-white text-xs font-bold flex items-center justify-center">{wishlistCount}</span>}</button></div>
  </div><div className="md:hidden flex items-center justify-around py-2.5 border-t border-stone-900 font-medium text-xs text-stone-400"><button onClick={()=>setActiveTab('explore')} className={active('explore')}>Cafes</button><button onClick={()=>setActiveTab('quick')} className={active('quick')}>10s Quick</button><button onClick={()=>setActiveTab('plans')} className={active('plans')}>Plans</button><button onClick={()=>setActiveTab('metro')} className={active('metro')}>Metro</button></div></div></header>;
}
