import React, { useMemo, useState } from 'react';
import { Search, MapPin, Users, Wallet, Sparkles, Globe } from 'lucide-react';
import { DISCOVERY_CAFES } from '../data/discoveryCafes';

const DEFAULT_FORM={location:'',budget:'1000',people:'2',vibe:'Any vibe',requirements:''};
const labels=['Best overall match','Best value','Best ambience','Best food option','Strong match','Good alternative'];
const upper=(value)=>{const nums=String(value||'').match(/[0-9][0-9,]*/g)||[];return nums.length?Number(nums[nums.length-1].replace(/,/g,'')):Infinity;};
const terms=(value)=>String(value||'').toLowerCase().split(/[\s,/-]+/).filter(Boolean).filter(t=>!['delhi','ncr','new','india'].includes(t));

export default function RecommendationPlanner({cafes=[]}){
 const [form,setForm]=useState(DEFAULT_FORM);const [results,setResults]=useState([]);const [searched,setSearched]=useState(false);
 const catalogue=useMemo(()=>{const m=new Map();[...cafes,...DISCOVERY_CAFES].forEach(c=>m.set(c.id||c.name,c));return [...m.values()];},[cafes]);
 const update=(k,v)=>setForm(p=>({...p,[k]:v}));
 const findPlaces=(e)=>{e.preventDefault();const budget=Number(form.budget),people=Number(form.people),loc=terms(form.location),vibe=form.vibe.toLowerCase(),req=form.requirements.toLowerCase();
  const ranked=catalogue.map(c=>{const hay=`${c.name} ${c.zone} ${c.bestFor||''} ${c.vibeTag||''} ${c.whatToOrder||''}`.toLowerCase();const cost=upper(c.budget)*(people/2);let score=c.isTopPick?8:0;const area=!loc.length||loc.some(t=>hay.includes(t));if(area&&loc.length)score+=35;if(vibe!=='any vibe'){if(hay.includes(vibe))score+=14;else if(vibe==='romantic'&&/aesthetic|quiet|outdoor/.test(hay))score+=6;}if(req)score+=req.split(/[, ]+/).filter(Boolean).slice(0,8).filter(t=>hay.includes(t)).length*3;if(Number.isFinite(cost)){if(cost<=budget)score+=24;else if(cost<=budget*1.15)score+=5;else score-=20;}return {...c,_score:score,_area:area,_cost:cost};}).sort((a,b)=>b._score-a._score);
  const areaPool=loc.length&&ranked.some(c=>c._area)?ranked.filter(c=>c._area):ranked;const budgetPool=areaPool.filter(c=>!Number.isFinite(c._cost)||c._cost<=budget*1.15);const pool=(budgetPool.length>=3?budgetPool:areaPool).slice(0,6);
  setResults(pool.map((c,i)=>({...c,matchLabel:labels[i]||'Good alternative',reason:loc.length&&c._area?`${c.zone} matches your area. ${c.curatorTake||c.bestFor||'A strong fit for your preferences.'}`:`${c.curatorTake||c.bestFor||'A strong fit for your preferences.'}`,budgetFit:Number.isFinite(c._cost)?`Approx. ₹${Math.round(c._cost).toLocaleString('en-IN')} for ${people}. Your target is ₹${Number(form.budget).toLocaleString('en-IN')}.`:`Price not reliably listed. Target ₹${Number(form.budget).toLocaleString('en-IN')}.`,caution:'Prices, hours and offers can change. Check the venue before visiting.'})));setSearched(true);};
 return <section id="find-my-place" className="bg-[#CC3A63] px-4 sm:px-6 lg:px-8 py-12 sm:py-16"><div className="max-w-6xl mx-auto"><div className="max-w-3xl mb-8"><div className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-[#FFF7EB]/80 mb-3"><Sparkles className="w-4 h-4"/> Personalized restaurant finder</div><h2 className="font-serif text-3xl sm:text-5xl font-bold text-[#241F1A]">Tell us what you want. We'll pick the places.</h2><p className="mt-3 text-sm sm:text-base text-[#FFF7EB]/90 leading-relaxed">Pick your Delhi NCR area, budget, group size and mood. We recommend only from our manually curated restaurant and cafe catalogue.</p></div>
 <form onSubmit={findPlaces} className="rounded-[28px] bg-[#F9F0E0] border border-[#A2AB73]/60 p-5 sm:p-7 shadow-xl"><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
 <label className="lg:col-span-2"><span className="text-xs font-bold uppercase tracking-wider text-[#56602E]">Where?</span><div className="relative mt-2"><MapPin className="absolute left-3 top-3.5 w-4 h-4 text-[#CC3A63]"/><input required value={form.location} onChange={e=>update('location',e.target.value)} placeholder="CP, Saket, Rajouri Garden, Dwarka, Noida, Gurgaon..." className="w-full pl-10 pr-3 py-3 rounded-xl bg-[#FFF7EB] border border-[#A2AB73]/50 outline-none focus:ring-2 focus:ring-[#CC3A63]/30"/></div></label>
 <label><span className="text-xs font-bold uppercase tracking-wider text-[#56602E]">Budget for everyone</span><div className="relative mt-2"><Wallet className="absolute left-3 top-3.5 w-4 h-4 text-[#CC3A63]"/><select value={form.budget} onChange={e=>update('budget',e.target.value)} className="w-full pl-10 pr-3 py-3 rounded-xl bg-[#FFF7EB] border border-[#A2AB73]/50"><option value="700">₹700</option><option value="1000">₹1,000</option><option value="1500">₹1,500</option><option value="2000">₹2,000</option><option value="3000">₹3,000+</option></select></div></label>
 <label><span className="text-xs font-bold uppercase tracking-wider text-[#56602E]">People</span><div className="relative mt-2"><Users className="absolute left-3 top-3.5 w-4 h-4 text-[#CC3A63]"/><select value={form.people} onChange={e=>update('people',e.target.value)} className="w-full pl-10 pr-3 py-3 rounded-xl bg-[#FFF7EB] border border-[#A2AB73]/50"><option value="1">1 person</option><option value="2">2 people</option><option value="3">3 people</option><option value="4">4 people</option><option value="6">5–6 people</option><option value="8">7–8 people</option><option value="10">9–10 people</option></select></div></label>
 <label><span className="text-xs font-bold uppercase tracking-wider text-[#56602E]">Vibe</span><select value={form.vibe} onChange={e=>update('vibe',e.target.value)} className="mt-2 w-full px-3 py-3 rounded-xl bg-[#FFF7EB] border border-[#A2AB73]/50"><option>Any vibe</option><option>Romantic</option><option>Quiet</option><option>Aesthetic</option><option>Casual</option><option>Youthful</option><option>Rooftop</option><option>Outdoor</option><option>Lively</option></select></label>
 <label className="md:col-span-2 lg:col-span-3"><span className="text-xs font-bold uppercase tracking-wider text-[#56602E]">Anything else?</span><input value={form.requirements} onChange={e=>update('requirements',e.target.value)} placeholder="e.g. Italian, vegetarian, dinner + walk, birthday cake, outdoor seating..." className="mt-2 w-full px-3 py-3 rounded-xl bg-[#FFF7EB] border border-[#A2AB73]/50 outline-none focus:ring-2 focus:ring-[#CC3A63]/30"/></label>
 <div className="flex items-end"><button className="w-full py-3.5 rounded-xl bg-[#CC3A63] text-white font-bold flex items-center justify-center gap-2 hover:bg-[#B52F55] shadow-md"><Search className="w-5 h-5"/>Find My Places</button></div></div></form>
 {searched&&<div className="mt-9"><div className="flex flex-wrap items-end justify-between gap-3 mb-5"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#FFF7EB]/80">CURATED DELHI NCR GUIDE</p><h3 className="font-serif text-2xl sm:text-3xl font-bold text-[#241F1A]">Your best matches</h3></div><span className="text-xs bg-[#F9F0E0] text-[#56602E] px-3 py-1.5 rounded-full border border-[#A2AB73]/50">{results.length} suggestions</span></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">{results.map((p,i)=><article key={p.id||`${p.name}-${i}`} className="rounded-3xl bg-[#F9F0E0] border border-[#A2AB73]/50 overflow-hidden shadow-lg flex flex-col"><div className="p-5 flex-1"><span className="text-[10px] uppercase tracking-wider font-bold text-[#CC3A63]">{p.matchLabel}</span><h4 className="font-serif text-xl font-bold text-[#332B23] mt-1">{p.name}</h4><p className="text-xs text-[#786C5C] mt-2">{p.zone}</p><div className="flex flex-wrap gap-2 mt-3"><span className="text-xs font-bold text-[#56602E]">{p.budget}</span><span className="text-xs text-[#786C5C]">{p.vibeTag}</span></div><p className="mt-4 text-sm text-[#4E453B] leading-relaxed">{p.reason}</p><p className="mt-2 text-xs text-[#56602E]"><b>Budget:</b> {p.budgetFit}</p><p className="mt-2 text-xs text-[#786C5C]"><b>Order idea:</b> {p.whatToOrder}</p><p className="mt-3 text-xs text-[#8F2E46]">{p.caution}</p></div><div className="grid grid-cols-2 gap-2 p-4 pt-0"><a href={p.mapsUrl} target="_blank" rel="noopener noreferrer" className="py-2.5 rounded-xl bg-[#A2AB73] text-white text-xs font-bold text-center flex items-center justify-center gap-1"><MapPin className="w-3.5 h-3.5"/> Maps</a><a href={p.zomatoUrl} target="_blank" rel="noopener noreferrer" className="py-2.5 rounded-xl bg-[#CC3A63] text-white text-xs font-bold text-center">Zomato</a>{p.websiteUrl&&<a href={p.websiteUrl} target="_blank" rel="noopener noreferrer" className="col-span-2 py-2.5 rounded-xl bg-[#FFF7EB] text-[#56602E] border border-[#A2AB73]/40 text-xs font-bold text-center flex items-center justify-center gap-1"><Globe className="w-3.5 h-3.5"/> Website</a>}</div></article>)}</div></div>}
 </div></section>;
}
