import React from 'react';
import { X, Heart, MapPin, Trash2 } from 'lucide-react';

export default function WishlistDrawer({ isOpen, onClose, wishlist, cafes, onToggleWishlist, onSelectCafe }) {
  if (!isOpen) return null;
  const wishlistedCafes = cafes.filter(c => wishlist.includes(c.id));
  return <div className="fixed inset-0 z-50 overflow-hidden bg-[#241F1A]/60 backdrop-blur-sm animate-fadeIn"><div className="absolute inset-y-0 right-0 max-w-full flex pl-10"><div className="w-screen max-w-md bg-[#FFF7EB] border-l border-[#A2AB73]/50 text-[#332B23] shadow-2xl flex flex-col justify-between">
    <div className="p-6 border-b border-[#A2AB73]/30 flex items-center justify-between"><div className="flex items-center space-x-2"><Heart className="w-6 h-6 text-[#CC3A63] fill-[#CC3A63]" /><h2 className="font-serif text-xl font-bold">Saved Wishlist ({wishlistedCafes.length})</h2></div><button onClick={onClose} className="p-2 rounded-xl bg-[#F9F0E0] text-[#56602E] border border-[#A2AB73]/40"><X className="w-5 h-5" /></button></div>
    <div className="p-6 overflow-y-auto flex-1 space-y-4">{wishlistedCafes.length ? wishlistedCafes.map(cafe=><div key={cafe.id} className="p-4 rounded-2xl bg-[#F9F0E0] border border-[#A2AB73]/40 space-y-2"><div className="flex items-start justify-between"><div><span className="text-[10px] font-bold uppercase tracking-wider text-[#CC3A63] block">{cafe.zone}</span><h4 onClick={()=>{onSelectCafe(cafe);onClose();}} className="font-serif text-lg font-bold hover:text-[#CC3A63] cursor-pointer">{cafe.name}</h4></div><button onClick={()=>onToggleWishlist(cafe.id)} className="p-1.5 rounded-lg bg-[#FFF7EB] text-[#6D7650] border border-[#A2AB73]/40"><Trash2 className="w-4 h-4" /></button></div><div className="flex items-center justify-between text-xs text-[#6D5E55]"><span className="text-[#56602E] font-bold">{cafe.budget}</span><a href={cafe.mapsUrl} target="_blank" rel="noopener noreferrer" className="text-[#CC3A63] hover:underline flex items-center gap-1"><MapPin className="w-3 h-3" /> Map Link</a></div></div>) : <div className="py-16 text-center text-[#6D5E55]"><Heart className="w-12 h-12 text-[#A2AB73] mx-auto mb-3" /><p className="font-serif text-lg font-bold text-[#332B23]">Your Wishlist is Empty</p><p className="text-xs mt-1">Click the heart icon on any cafe card to save it here.</p></div>}</div>
    <div className="p-6 border-t border-[#A2AB73]/30 bg-[#F9F0E0] text-xs text-[#6D5E55] text-center">Wishlist items are automatically saved in your browser local storage.</div>
  </div></div></div>;
}
